### ISSUE TITLE
lancet 1.0.7 does not build (Centos 7.4.1708, gcc 4.8.5)

### ISSUE THREAD

**Issue by jbsysadmin** [nygenome/lancet#31]
Hello again. 
I had access to a newer build environment, and wanted to see if lancet "make" would succeed there. 

I compiled cmake-3.12.1 to resolve an error; in-OS version was still too old. However, this fails with the error at bottom. Installing openssl-libs and openssl did not work. What depdendency should be installed to resolve "cannot find -lcrypto" ?

*** error excerpt ***

FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::p’ was declared here
   hgacc_t aux;
           ^
/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
make[1]: *** [lancet] Error 1
make[1]: Leaving directory `/usr/local/installs/lancet-1.0.7/src'

**Comment by gnarzisi** [comment]
the error `/bin/ld: cannot find -lcrypto` means that you are missing some of the development libraries. This link provides a solution:

https://github.com/znort987/blockparser/issues/38

**Comment by jbsysadmin** [comment]
Hello again.

The problems here seem to start with lancet build using it’s own htslib-1.8, in a subdirectory. Is there any way to point that to a version we’ve already compiled, on a different path?

-John

*****************
[edit]
make[1]: Leaving directory `/usr/local/installs/lancet-1.0.7/htslib-1.8'
cd src; make; cp lancet ../; cd ../
make[1]: Entering directory `/usr/local/installs/lancet-1.0.7/src'
g++ -std=c++0x -Wno-deprecated -Wall -O3 -fexceptions -g -Wl,-rpath,/usr/local/installs/lancet-1.0.7/bamtools-2.5.1/lib64/ -I/usr/local/installs/lancet-1.0.7/bamtools-2.5.1/include/bamtools -I/usr/local/installs/lancet-1.0.7/htslib-1.8/ -L/usr/local/installs/lancet-1.0.7/bamtools-2.5.1/lib64/ -L/usr/local/installs/lancet-1.0.7/htslib-1.8/ Lancet.cc Edge.cc Node.cc Graph.cc Microassembler.cc Ref.cc Path.cc ContigLink.cc align.cc util.cc sha256.cc VariantDB.cc Variant.cc -o lancet /usr/local/installs/lancet-1.0.7/htslib-1.8/libhts.a -llzma -lbz2 -lz -ldl -lpthread -lcurl -lcrypto -lbamtools
In file included from Variant.hh:36:0,
                 from Variant.cc:1:
FET.hh: In member function ‘double Variant_t::compute_FET_score()’:
FET.hh:71:22: warning: ‘aux.FET_t::hgacc_t::n’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                      ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:31: warning: ‘aux.FET_t::hgacc_t::n1_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n1_’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:15: warning: ‘aux.FET_t::hgacc_t::n_1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n_1’ was declared here
   hgacc_t aux;
           ^
FET.hh:72:25: warning: ‘aux.FET_t::hgacc_t::n11’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (n11 == aux->n11 + 1) { // incremental
                         ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n11’ was declared here
   hgacc_t aux;
           ^
FET.hh:74:69: warning: ‘aux.FET_t::hgacc_t::p’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       * (aux->n_1 - aux->n11) / (n11 + aux->n - aux->n1_ - aux->n_1);
                                                                     ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::p’ was declared here
  hgacc_t aux;
           ^
FET.hh: In member function ‘double Variant_t::compute_SB_score()’:
FET.hh:71:22: warning: ‘aux.FET_t::hgacc_t::n’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                      ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:31: warning: ‘aux.FET_t::hgacc_t::n1_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n1_’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:15: warning: ‘aux.FET_t::hgacc_t::n_1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n_1’ was declared here
   hgacc_t aux;
           ^
FET.hh:72:25: warning: ‘aux.FET_t::hgacc_t::n11’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (n11 == aux->n11 + 1) { // incremental
                         ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n11’ was declared here
   hgacc_t aux;
           ^
FET.hh:74:69: warning: ‘aux.FET_t::hgacc_t::p’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       * (aux->n_1 - aux->n11) / (n11 + aux->n - aux->n1_ - aux->n_1);
                                                                     ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::p’ was declared here
   hgacc_t aux;
           ^
/nfs/goldstein/software/binutils-2.26.1/bin/ld: /tmp/ccStFL1D.o: undefined reference to symbol 'clock_gettime@@GLIBC                 _2.2.5'
/lib64/librt.so.1: error adding symbols: DSO missing from command line

**Comment by jbsysadmin** [comment]
Oh, pardon my last!
To clarify, I switched back to Centos 6 and gcc-4.9.3 for this. Cmake is now at 3.12.1.
Under Centos 7,  lancet 1.0.7  seemed to build finally. But I wasn’t allowed to present it because there weren’t enough hosts with the new OS.

From: Burns, W. J.
Sent: Tuesday, August 21, 2018 12:25 PM
To: 'nygenome/lancet' <reply@reply.github.com>; nygenome/lancet <lancet@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [nygenome/lancet] lancet 1.0.7 does not build (Centos 7.4.1708, gcc 4.8.5) (#31)

Hello again.

The problems here seem to start with lancet build using it’s own htslib-1.8, in a subdirectory. Is there any way to point that to a version we’ve already compiled, on a different path?

-John

*****************
[edit]
make[1]: Leaving directory `/usr/local/installs/lancet-1.0.7/htslib-1.8'
cd src; make; cp lancet ../; cd ../
make[1]: Entering directory `/usr/local/installs/lancet-1.0.7/src'
g++ -std=c++0x -Wno-deprecated -Wall -O3 -fexceptions -g -Wl,-rpath,/usr/local/installs/lancet-1.0.7/bamtools-2.5.1/lib64/ -I/usr/local/installs/lancet-1.0.7/bamtools-2.5.1/include/bamtools -I/usr/local/installs/lancet-1.0.7/htslib-1.8/ -L/usr/local/installs/lancet-1.0.7/bamtools-2.5.1/lib64/ -L/usr/local/installs/lancet-1.0.7/htslib-1.8/ Lancet.cc Edge.cc Node.cc Graph.cc Microassembler.cc Ref.cc Path.cc ContigLink.cc align.cc util.cc sha256.cc VariantDB.cc Variant.cc -o lancet /usr/local/installs/lancet-1.0.7/htslib-1.8/libhts.a -llzma -lbz2 -lz -ldl -lpthread -lcurl -lcrypto -lbamtools
In file included from Variant.hh:36:0,
                 from Variant.cc:1:
FET.hh: In member function ‘double Variant_t::compute_FET_score()’:
FET.hh:71:22: warning: ‘aux.FET_t::hgacc_t::n’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                      ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:31: warning: ‘aux.FET_t::hgacc_t::n1_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n1_’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:15: warning: ‘aux.FET_t::hgacc_t::n_1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n_1’ was declared here
   hgacc_t aux;
           ^
FET.hh:72:25: warning: ‘aux.FET_t::hgacc_t::n11’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (n11 == aux->n11 + 1) { // incremental
                         ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n11’ was declared here
   hgacc_t aux;
           ^
FET.hh:74:69: warning: ‘aux.FET_t::hgacc_t::p’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       * (aux->n_1 - aux->n11) / (n11 + aux->n - aux->n1_ - aux->n_1);
                                                                     ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::p’ was declared here
  hgacc_t aux;
           ^
FET.hh: In member function ‘double Variant_t::compute_SB_score()’:
FET.hh:71:22: warning: ‘aux.FET_t::hgacc_t::n’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                      ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:31: warning: ‘aux.FET_t::hgacc_t::n1_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n1_’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:15: warning: ‘aux.FET_t::hgacc_t::n_1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n_1’ was declared here
   hgacc_t aux;
           ^
FET.hh:72:25: warning: ‘aux.FET_t::hgacc_t::n11’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (n11 == aux->n11 + 1) { // incremental
                         ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n11’ was declared here
   hgacc_t aux;
           ^
FET.hh:74:69: warning: ‘aux.FET_t::hgacc_t::p’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       * (aux->n_1 - aux->n11) / (n11 + aux->n - aux->n1_ - aux->n_1);
                                                                     ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::p’ was declared here
   hgacc_t aux;
           ^
/nfs/goldstein/software/binutils-2.26.1/bin/ld: /tmp/ccStFL1D.o: undefined reference to symbol 'clock_gettime@@GLIBC                 _2.2.5'
/lib64/librt.so.1: error adding symbols: DSO missing from command line

**Comment by gnarzisi** [comment]
Glad to hear that lancet compiled on Centos 7.  Have you tried if, by luck, the binary works under Centos 6 directly?

If you want the code to point to a different htslib, you will need to update the Makefile in the src/ directory accordingly (never tried before though). The lines to look for are:

```
INCLUDES := -I$(ABS_BAMTOOLS_DIR)/include/bamtools -I$(ABS_HTSLIB_DIR)/
LDFLAGS := -L$(ABS_BAMTOOLS_DIR)/lib64/ -L$(ABS_HTSLIB_DIR)/
```

**Comment by jbsysadmin** [comment]
Please close this issue. We are handling the dependencies through in-OS packages. But do see issue #35.

**Comment by medcelerate** [comment]
I am getting this same error when trying to build in the container.

**Comment by medcelerate** [comment]
Having the same issue . on centos 7 docker ET.hh:95:11: warning: 'aux.FET_t::hgacc_t::n_1' may be used uninitialized in this function

**Comment by gnarzisi** [comment]
It looks like you have just a warning (not a compilation error). Was the binary created? If yes, it should be working fine.

**Comment by medcelerate** [comment]
Yes the binary was created however when trying to run it there is a segmentation fault.

**Comment by gnarzisi** [comment]
Does the segmentation fault error happen when running just the help command? 

`lancet -h`

Or when passing BAM and FASTA files in input ?

**Comment by medcelerate** [comment]
It does not happen when running help, passing bam files is when it happens

**Comment by gnarzisi** [comment]
In that case the binary compiled successfully. 

My guess is that the BAM, FASTA, and/or BED may not be compatible to each other. Ideally the same reference file that was used to align the reads in the BAM should be used in input. Also, if using a BED file, make sure the chromosome labels are the same as the ones in the BAM and reference FASTA.

**Comment by medcelerate** [comment]
Fasta and bam or for sure the same. I can check the bed file.
